### ISSUE TITLE
bootstrap directory should be ignored or how can we ignore any directory or file?

### ISSUE THREAD

**Issue by Jagdish-J-P** [TheDragonCode/codestyler#82]
### Feature description

When we execute codestyle check/fix - It is also checking bootstrap directory and cache directory in laravel.

I need to know is there any option to ignore specific directory? And if there is no option then how can we ignore specific directory or file?

### Envoronment

- Code Styler Version: 2.1.0
- PHP Version: 8.1

**Comment by andrey-helldar** [comment]
By default, the following directories are [ignored](https://github.com/TheDragonCode/codestyler/blob/main/rules/main.php#L8-L15):

```
.git
.github
.idea
node_modules
vendor
```

At the moment, it is not possible to use custom paths, but we will add this functionality in the near future.

**Comment by andrey-helldar** [comment]
Sorry for the long wait.

We will not add the ability to use custom paths for exceptions.

1. php-cs-fixer does not allow you to pass exception commands as parameters - it requires a link to a physical configuration file.
2. Creating a configuration file on the fly, using a file saved in the project and merging with ours, is a bad idea.

Since we most often work with the Laravel framework, which uses the "bootstrap" directory to store cached data, we decided to add this folder to the exclusions.

This change is released in version [`2.6.0`](https://github.com/TheDragonCode/codestyler/releases/tag/v2.6.0).

**Comment by Jagdish-J-P** [comment]
Thank you for the update
